version: 2
make_run: &make_run
  docker:
    - image: golang:1.13.7
  steps:
    - checkout
    - run:
        name: Packer Run
        command: |
          set -e
          go build
          make $MAKE_COMMAND
jobs:
  lint:
    <<: *make_run
    environment:
      MAKE_COMMAND: "lint"
  test:
    <<: *make_run
    environment:
      MAKE_COMMAND: "test"
  build:
    <<: *make_run
    environment:
      MAKE_COMMAND: ""
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
